import * as React from "react";
import Head from "next/head";
import styles from "../styles/home.module.css";
import Room, { BaseRoomProps } from "../components/room";
import _cloneDeep from "lodash/cloneDeep";
import { useWindowSize } from "react-use";

function createRoomProps() {
    return {
        transform: {
            w: Math.random() / 6 + 0.1,
            h: Math.random() / 6 + 0.1,
            x: Math.random(),
            y: Math.random(),
        },
        duration: Math.random() * 2 + 1,
    };
}

interface HomeProps {
    rooms: BaseRoomProps[];
}

export default function Home({ rooms: initRooms }: HomeProps) {
    const [rooms, setRooms] = React.useState(() => initRooms);
    const { width, height } = useWindowSize();

    function click(e: React.MouseEvent) {
        const newRooms: ReturnType<typeof createRoomProps>[] = [];

        for (const room of rooms) {
            const newRoom = _cloneDeep(room);
            newRoom.transform.x = e.clientX / width;
            newRoom.transform.y = e.clientY / height;
            newRooms.push(newRoom);
        }

        console.log("newRooms = ", newRooms);
        setRooms(newRooms);
    }

    return (
        <div className={styles.container} onClick={click}>
            <Head>
                <title>This Liver</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {typeof window !== "undefined" &&
                rooms.map((room, i) => (
                    <Room key={i} {...room}>
                        LIVER
                    </Room>
                ))}

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Liver</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{" "}
                    <code className={styles.code}>Liver</code>
                </p>
            </main>
        </div>
    );
}

export function getServerSideProps() {
    const rooms = [];
    for (let i = 0; i < 10; i++) {
        rooms.push(createRoomProps());
    }
    return { props: { rooms } };
}
